baseurl = "http://yuhuan.world/"
title = "Yuhuan's Blog"
theme = "ghostwriter"

[author]
  name = "Yuhuan Fan"
  homepage = "https://yuhuan.world/"

# main section
[Params]
  disqus = "yuhuan"
  mainSections = ["post"]
  intro = true
  headline = "My headline"
  description = "My description"
  github = "https://github.com/XXX"
  twitter = "https://twitter.com/XXX"
  email = "XXX@example.com"
  opengraph = true
  shareTwitter = true
  dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
  post = "/:filename/"  