baseURL = "http://yuhuan.world/"
languageCode = "en-us"
title = "Yuhuan's Blog"
theme = "yinyang"
DefaultContentLanguage = "en"

[author]
  name = "Yuhuan Fan"
  homepage = "https://yuhuan.world/"

# Multi-Language
[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

# main section
[params]
disqus = "yuhuan"
mainSections = ["posts"]
# extra head
# extraHead = '<script src=""></script>'

# header / footer in every post
# postHeaderContent = ""
# postFooterContent = "<br/><br/><p>Subscribe：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"

# footer
[[params.socials]]
name = "About Me"
link = "http://www.yuhuan.world/blog/"

[[params.socials]]
name = "Github"
link = "https://github.com/Yuhuan0207"

[[params.socials]]
name = "Linkedin"
link = "https://www.linkedin.com/in/yfan4/"